{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.aefyr",
    "module": "flexfilter-config-ui",
    "version": "0.9-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flexfilter-config-ui-0.9-alpha.aar",
          "url": "flexfilter-config-ui-0.9-alpha.aar",
          "size": 40435,
          "sha512": "e4607a0e994b0874ccdd38fb87fb62c92717a28ef0d054e6fab72c816f7dda3d95cb0d5725a1874753830540d4bfd9365bca295ef59db25143c7e72334677134",
          "sha256": "e10f2346208513451c113f8ab702fabe469f29f0054cf3b242fbef260b5866ef",
          "sha1": "e11db7eaf2efcce6645ed854b06c6b328aea9bba",
          "md5": "ce0fb41cdbb364b51d3feaf5be21c638"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.aefyr",
          "module": "flexfilter-config-core",
          "version": {
            "requires": "0.9-alpha"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flexfilter-config-ui-0.9-alpha.aar",
          "url": "flexfilter-config-ui-0.9-alpha.aar",
          "size": 40435,
          "sha512": "e4607a0e994b0874ccdd38fb87fb62c92717a28ef0d054e6fab72c816f7dda3d95cb0d5725a1874753830540d4bfd9365bca295ef59db25143c7e72334677134",
          "sha256": "e10f2346208513451c113f8ab702fabe469f29f0054cf3b242fbef260b5866ef",
          "sha1": "e11db7eaf2efcce6645ed854b06c6b328aea9bba",
          "md5": "ce0fb41cdbb364b51d3feaf5be21c638"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flexfilter-config-ui-0.9-alpha-sources.jar",
          "url": "flexfilter-config-ui-0.9-alpha-sources.jar",
          "size": 7012,
          "sha512": "444852b464a124486ee24cae4bb8ce2b38a0bf06667abee6307afea54bb1869ab81601b7bbba623a9b152e458bb883de7fd97271dc8c9161d797842acda73404",
          "sha256": "fe788c372724d539bdae519b67ebf76a78a32c11f3306e373466684023163d39",
          "sha1": "48d352fb4970fa6e8adfda3b9c8b8339ab2b9e27",
          "md5": "ed27a0e18a83d5a8dff85dfb6eb9ede1"
        }
      ]
    }
  ]
}
